# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: sc_back_development
  pool: 5
  username: pur100
  password:
  timeout: 5000

test:
 adapter: postgresql
 encoding: unicode
 database: sc_back_test
 pool: 5
 username: pur100
 password:
 timeout: 5000
